import LocalWorkflowStudioCore

struct MockEngineClient: WorkflowEngineClientProtocol {
    var result: EngineRunResult

    func generateNode(intent: String, context: [String: JSONValue]) async throws -> ExecutableNode {
        ExecutableNode(
            id: "a7cd860d-78d9-4bfc-a5af-36f430cbd456",
            meta: ExecutableMeta(app: "filesystem", category: "file", action: "write_file", label: "Write local result", source: "manual"),
            fields: [
                ExecutableField(id: "path", type: "string", required: true, label: "File path", value: "/tmp/nexus-native-result.txt"),
                ExecutableField(id: "content", type: "string", required: true, label: "Content", value: "Generated by local AI")
            ],
            runner: ExecutableRunner(
                steps: [RunnerStep(primitive: "fs_write", args: ["path": .string("{{fields.path}}"), "content": .string("{{fields.content}}")])],
                output_binding: nil
            ),
            mcp: nil
        )
    }

    func runNode(_ node: ExecutableNode, context: [String: JSONValue]) async throws -> EngineRunResult {
        result
    }

    func listNodes() async throws -> [ExecutableNode] {
        [try await generateNode(intent: "saved", context: [:])]
    }

    func createLifePlan(text: String) async throws -> LifePlan {
        sampleLifePlan()
    }
}

final class RecordingEngineClient: @unchecked Sendable, WorkflowEngineClientProtocol {
    var runIDs: [String] = []
    var contexts: [[String: JSONValue]] = []

    func generateNode(intent: String, context: [String: JSONValue]) async throws -> ExecutableNode {
        node(id: "11111111-1111-4111-8111-111111111111", label: "First")
    }

    func runNode(_ node: ExecutableNode, context: [String: JSONValue]) async throws -> EngineRunResult {
        runIDs.append(node.id)
        contexts.append(context)
        return EngineRunResult(output: .string(node.meta.label), error: nil, failed_step: nil)
    }

    func listNodes() async throws -> [ExecutableNode] {
        [node(id: "22222222-2222-4222-8222-222222222222", label: "Second")]
    }

    func createLifePlan(text: String) async throws -> LifePlan {
        sampleLifePlan()
    }

    private func node(id: String, label: String) -> ExecutableNode {
        ExecutableNode(
            id: id,
            meta: ExecutableMeta(app: "test", category: "graph", action: label, label: label, source: "manual"),
            fields: [],
            runner: ExecutableRunner(steps: [RunnerStep(primitive: "shell_run", args: ["command": .string("true")])], output_binding: nil),
            mcp: nil
        )
    }
}

@main
@MainActor
struct ModelTestRunner {
    static func main() async {
        testAppStartsEmpty()
        await testGenerateWorkflowCreatesExecutableCanvas()
        await testApprovalBlocksAndThenAllowsBackendRun()
        await testChangingExecutableJSONInvalidatesApproval()
        await testCanvasEditingInvalidatesApproval()
        await testFailureReporting()
        await testSavedNodesLoad()
        await testLoadedNodesAppendAndConnectionsRejectCycles()
        await testGraphExecutesConnectedNodesInOrder()
        await testLifePlanCreatesAssistantBrief()
        await testLifePlanCanBuildWorkflow()
        print("LocalWorkflowStudioNativeModelTests passed")
    }

    static func model(result: EngineRunResult = EngineRunResult(output: .string("wrote file"), error: nil, failed_step: nil)) -> StudioModel {
        StudioModel(engineClient: MockEngineClient(result: result))
    }

    static func generatedModel() async -> StudioModel {
        let model = model()
        model.prompt = "Write Generated by local AI to /tmp/nexus-native-result.txt"
        await model.generateWorkflowFromBackend()
        return model
    }

    static func testAppStartsEmpty() {
        let model = model()
        precondition(model.prompt.isEmpty)
        precondition(!model.hasWorkflow)
        precondition(model.logs.isEmpty)
        precondition(model.runnerStatus == "Idle")
    }

    static func testGenerateWorkflowCreatesExecutableCanvas() async {
        let model = await generatedModel()
        precondition(model.hasWorkflow)
        precondition(model.workflow.nodes.count == 1)
        precondition(model.workflow.nodes.first?.title == "Write local result")
        precondition(model.workflow.executableNode?.runner.steps.first?.primitive == "fs_write")
        precondition(model.workflow.rawScript.contains("\"fs_write\""))
        model.dryRun()
        precondition(model.logs.contains(where: { $0.node == "Dry Run" && $0.message.contains("1 canvas node") }))
    }

    static func testApprovalBlocksAndThenAllowsBackendRun() async {
        let model = await generatedModel()
        await model.runLocallyWithBackend()
        precondition(model.runnerStatus == "Blocked")
        model.approveVersion()
        await model.runLocallyWithBackend()
        precondition(model.runnerStatus == "Complete")
        precondition(model.workflow.executionOutput == "wrote file")
    }

    static func testChangingExecutableJSONInvalidatesApproval() async {
        let model = await generatedModel()
        model.approveVersion()
        precondition(!model.approvalRequired)
        model.workflow.rawScript += "\nchanged"
        precondition(model.approvalRequired)
    }

    static func testCanvasEditingInvalidatesApproval() async {
        let model = await generatedModel()
        model.approveVersion()
        let node = model.workflow.nodes[0]
        model.setNodePosition(id: node.id, x: node.x + 80, y: node.y + 40)
        precondition(model.selectedNode?.id == node.id)
        precondition(model.approvalRequired)
    }

    static func testFailureReporting() async {
        let model = model(result: EngineRunResult(output: nil, error: "permission denied", failed_step: 0))
        model.prompt = "Write a protected file"
        await model.generateWorkflowFromBackend()
        model.approveVersion()
        await model.runLocallyWithBackend()
        precondition(model.runnerStatus == "Failed")
        precondition(model.logs.contains(where: { $0.node == "Runner" && $0.message.contains("permission denied") }))
    }

    static func testSavedNodesLoad() async {
        let model = model()
        await model.refreshSavedNodes()
        precondition(model.savedNodes.count == 1)
        model.loadSavedNode(model.savedNodes[0])
        precondition(model.hasWorkflow)
        precondition(model.runnerStatus == "Loaded")
    }

    static func testLoadedNodesAppendAndConnectionsRejectCycles() async {
        let model = await generatedModel()
        await model.refreshSavedNodes()
        model.loadSavedNode(model.savedNodes[0])
        precondition(model.workflow.nodes.count == 2)

        let first = model.workflow.nodes[0]
        let second = model.workflow.nodes[1]
        model.beginConnection(from: first.id)
        model.completeConnection(to: second.id)
        precondition(model.workflow.edges.count == 1)

        model.beginConnection(from: second.id)
        model.completeConnection(to: first.id)
        precondition(model.workflow.edges.count == 1)
        precondition(model.logs.contains(where: { $0.message.contains("would create a cycle") }))

        model.approveVersion()
        await model.runLocallyWithBackend()
        precondition(model.runnerStatus == "Complete")
        precondition(model.workflow.nodes.allSatisfy { $0.status == .success })
    }

    static func testGraphExecutesConnectedNodesInOrder() async {
        let client = RecordingEngineClient()
        let model = StudioModel(engineClient: client)
        model.prompt = "First"
        await model.generateWorkflowFromBackend()
        await model.refreshSavedNodes()
        model.loadSavedNode(model.savedNodes[0])

        let first = model.workflow.nodes[0]
        let second = model.workflow.nodes[1]
        model.beginConnection(from: first.id)
        model.completeConnection(to: second.id)
        model.approveVersion()
        await model.runLocallyWithBackend()

        precondition(client.runIDs == ["11111111-1111-4111-8111-111111111111", "22222222-2222-4222-8222-222222222222"])
        precondition(client.contexts[1]["nodes"] == .object(["0": .object(["output": .string("First")])]))
        precondition(model.workflow.executionOutput == "Second")
    }

    static func testLifePlanCreatesAssistantBrief() async {
        let model = model()
        model.prompt = "Title: Weekly reset\nTasks:\n- Send recap by tonight\nQuestions:\nWhat can wait?"
        await model.createLifePlanFromBackend()
        precondition(model.lifePlan?.title == "Weekly reset")
        precondition(model.lifePlan?.tasks.count == 1)
        precondition(model.lifePlan?.automations.first?.title == "Save command brief")
        precondition(model.runnerStatus == "Plan ready")
        precondition(model.logs.contains(where: { $0.node == "Life AI" && $0.message.contains("automation suggestion") }))
    }

    static func testLifePlanCanBuildWorkflow() async {
        let model = model()
        model.prompt = "Title: Weekly reset\nTasks:\n- Send recap by tonight"
        await model.createLifePlanFromBackend()
        await model.buildWorkflowFromLifePlanFromBackend()
        precondition(model.hasWorkflow)
        precondition(model.prompt.contains("write a string"))
        precondition(model.workflow.nodes.first?.title == "Write local result")
    }
}

func sampleLifePlan() -> LifePlan {
    LifePlan(
        id: "life-plan-test",
        title: "Weekly reset",
        date: "2026-06-01",
        context: "Personal command center intake",
        brief: "Weekly reset has one task and one open question.",
        sourceText: "Title: Weekly reset",
        stats: LifePlanStats(tasks: 1, resources: 0, questions: 1, automations: 1),
        tasks: [
            LifeTask(id: "task-send-recap-1", title: "Send recap", status: "todo", dueDateText: "tonight", priority: "high", source: "Send recap by tonight")
        ],
        resources: [],
        questions: [
            LifeQuestion(id: "question-wait-1", text: "What can wait?")
        ],
        nextMeeting: nil,
        automations: [
            LifeAutomation(
                id: "automation-save-brief",
                title: "Save command brief",
                intent: "write a string to /tmp/nexus-life-brief.md with content Weekly reset",
                impact: "Creates a local Markdown command brief.",
                riskLevel: "low",
                requiresApproval: true
            )
        ],
        warnings: ["Review before running."],
        rawSummary: "Weekly reset"
    )
}
